name: Build N64 Visualizer

on: 
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git cmake libpng-dev python3 \
          wget curl texinfo bison flex libgmp-dev libmpfr-dev libmpc-dev
    
    - name: Install libdragon
      run: |
        # Download and install libdragon with toolchain
        cd /opt
        sudo git clone --recursive https://github.com/DragonMinded/libdragon.git
        cd libdragon
        
        # Set environment
        export N64_INST=/opt/libdragon
        echo "N64_INST=/opt/libdragon" | sudo tee -a /etc/environment
        
        # Build toolchain first
        sudo -E ./tools/build-toolchain.sh /opt/libdragon
        
        # Then build libdragon
        sudo -E make -j$(nproc)
        sudo make install
      env:
        N64_INST: /opt/libdragon
    
    - name: Convert audio
      run: |
        python3 tools/wav_to_c.py intensidade-intro-mono-22050.wav intensidade_audio
    
    - name: Build ROM
      run: |
        source /etc/environment
        export N64_INST=/opt/libdragon
        export PATH=$PATH:/opt/libdragon/bin
        echo "PATH=$PATH"
        echo "N64_INST=$N64_INST"
        ls -la /opt/libdragon/bin/ || echo "bin directory not found"
        make clean
        make
      env:
        N64_INST: /opt/libdragon
    
    - name: Upload ROM
      uses: actions/upload-artifact@v4
      with:
        name: n64-visualizer-rom
        path: build/visualizer.z64
